### ISSUE TITLE
[Platform] Short Bug description

### ISSUE THREAD

**Issue by saposantosapo** [ArcadeTV/msu-md-sf2rm#5]
**Patch version**
Latest on your Github repository.

**Platform**
Are you playing on an emulator or real hardware?
MegaEDpro OS 4.11)

**Describe the bug**
The acelerated track when the player is near to dead is not triggered

**Additional context**

**Comment by ArcadeTV** [comment]
Since CD audio can not change its playback speed, additional  tracks would have been made for this. Also there is no way to determine where the current track is playing, so changing the speed would require to start a new track, this will always be from the beginning, so it doesn't make sense :-(
This is a limitation of the driver. I will have to requect this request until somebody updates the driver for this feature.
